
default:
    path:
        data:
            current: "/Volumes/shlab/Projects/BST/data/Current_Dataframes"
            survey: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/SurveyData"
            explicit: "/Volumes/shlab/Projects/BST/data/Current_Dataframes"
            cortisol: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/CortisolData"
        code:
            r_scripts: "./bst_analysis/bst_scripts"
    csvs:
        pss: "PSSData_noVarDescrip.csv"
        cort: "Cortisol_Data.csv"
        bath_pleasantness: "bathPleasantness.csv"
        bath_order: "bathOrder.csv"
        tg: "allTGData_20200626.csv"
        tr: "allTRData_20200626.csv"
        amp: "allAMPData_20200626.csv"
        iat: "allIATData_20200626.csv"
        srs: "BST_SymbolicRacismScale_Data.csv"
        mrs: "BST_ModernRacismScale_Data.csv"
        ims_ems: "BST_IMS_EMS_Data.csv"
        cm: "BST_ContactMeas_Data.csv"
        ptsD1: "BST_Data_CPTRating_PostTaskSurvey_D1.csv"
        ptsD2: "BST_Data_CPTRating_PostTaskSurvey_D2.csv"
    code_files:
        setup_data: "setup_data.R"
        main_analysis: "main_analysis.R"
        attitudes_analysis: "attitudes_analysis.R"
        stress_analysis: "stress_analysis.R"
        trust_analysis: "trust_analysis.R"
        interactive_analysis: "interactive_analysis.R"
        iat_analysis: "iat_analysis.R"
