
default:
  path:
    data:
        pss: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/SurveyData/PSSData_noVarDescrip.csv"
        bath_pleasantness: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/bathPleasantness.csv"
        bath_order: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/bathOrder.csv"
        tg: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/allTGData_20200626.csv"
        tr: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/allTRData_20200626.csv"
    code:
        setup_data: "./bst_analysis/stress_and_trust/setup_data.R"
