
default:
    path:
        data:
            current: "/Volumes/shlab/Projects/BST/data/Current_Dataframes"
            survey: "/Volumes/shlab/Projects/BST/data/Current_Dataframes/SurveyData"
        code:
            r_scripts: "./bst_analysis/stress_and_trust"
    csvs:
        pss: "PSSData_noVarDescrip.csv"
        bath_pleasantness: "bathPleasantness.csv"
        bath_order: "bathOrder.csv"
        tg: "allTGData_20200626.csv"
        tr: "allTRData_20200626.csv"
        amp: "allAMPData_20200626.csv"
        iat: "allIATData_20200626.csv"
    code_files:
        setup_data: "setup_data.R"
        main_analysis: "main_analysis.R"
